### ISSUE TITLE
400 error using google-signin and (probably) ss_domain parameter

### ISSUE THREAD

**Issue by jarrodek** [GoogleWebComponents/google-signin#101]
Hi,

I'm trying to implement google-signin button to my website. I did everything according to docs and it isn't working.
When I click on sign in button popup is opening but with 400 error. The same thing happening when I run demo app from component's directory.

I noticed that the popup's URL have "ss_domain" parameter. It's not documented so I don't know what it suppose to do. However when I remove it from the URL it works perfectly (I can see permissions dialog). This parameter has not been added by the component itself. As I can see it must be constructed somewhere inside gapi.auth2.getAuthInstance().signIn function from the auth2 library. 

I hope it can be fixed soon.

**Comment by Scarygami** [comment]
Usually the popup contains more detailed error information, e.g. something like `Error: redirect_uri_mismatch`

Could you copy/paste the complete error information here including the "Request Details"?

**Comment by tazik-castodia** [comment]
I'm having the same issue with `ss_domain` in localhost. My request works perfectly once I remove the parameter, which defaults to my origin. I can't find anything on it in the documentation, so any insight would be appreciated.
