### ISSUE TITLE
Obtain the auth'd users email in when signed in?

### ISSUE THREAD

**Issue by newfivefour** [GoogleWebComponents/google-signin#104]
Once the user has logged in, and `on-google-signin-success` has been called, there's no way of  getting the email address of whoever has auth'd.

Even when you've given access to:

```
Basic account info
Know who you are on Google
View your email address
View your basic profile info
```

In `handleUserUpdate: function(newPrimaryUser)` in `google-signin-aware.html` the user's email is there, but under an obfuscated property in the newPrimaryUser property.

The [docs](https://elements.polymer-project.org/elements/google-signin ) state that `google-signin-success` will be fired and we can use `gapi.auth2.getAuthInstance().currentUser.get()` to get the user.

But it's unclear what this means - can we elaborate?

**Comment by atotic** [comment]
That means:
- listen to google-signin-success event
- inside your event handler, use gapi.auth2.getAuthInstance().currentUser.get()  to get current user
