### ISSUE TITLE
google-signin-success event not fired on Chrome?

### ISSUE THREAD

**Issue by dulimarta** [GoogleWebComponents/google-signin#105]
<!DOCTYPE html>
    <html>
    <head>
      <script src="../bower_components/webcomponentsjs/webcomponents-lite.js"></script>
      <link rel="import" href="../bower_components/polymer/polymer.html">
      <link rel="import" href="../bower_components/google-signin/google-signin.html">   
      <script src="https://apis.google.com/js/platform.js" async defer></script>
    </head>
    <body>
      <google-signin id="signin" 
        client-id=".....[myclientid goes here]....." 
        scopes="email profile"></google-signin>
      <script>
        var el = document.querySelector("#signin");
        el.addEventListener('google-signin-success', function(e) {
          /* this function is never called by Chrome */
          var prof = gapi.auth2.getAuthInstance().currentUser.get().getBasicProfile();
          alert("I am here to sign in as " + prof.getName());
        });
     
        el.addEventListener('google-signed-out', function(e) {
          alert("I am here to SIGNOUT");
        });
      </script>
    </body>
    </html>

The signin sequence works in FireFox and Safari, but not in Chrome. The `google-signin-success` function handler was never invoked in Chrome. When the script is being loaded, I saw the following error in Chrome console:

    Uncaught SecurityError: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.           4085826231-idpiframe.js:19

What is the work around to make it work on Chrome?

PS: I am using Chrome 44.0.2403.157 (64-bit) and tried both normal and incognito window.

**Comment by atotic** [comment]
I've just tested it on Chrome and it works. The problem is your Chrome configuration. Google the error message, and you'll find suggestions on how to fix it. Ex:

http://stackoverflow.com/questions/24456891/iframe-in-chrome-error-uncaught-securityerror-failed-to-read-the-sessionstora

**Comment by geoffdavis92** [comment]
@atotic I am getting this error when loading my app from my saved home screen link on iOS:

`TypeError: null is not an object (evaluating 'this.$.getItem')`

Stack trace: ![Issue stack trace](http://i.imgur.com/VkCUKDs.png)

When I actually attempt to sign in, I get a blank screen and the following error message:

`TypeError: null is not an object (evaluating 'this.c.setItem')`

Stack trace: ![sign in dialogue stack trace](http://i.imgur.com/ryhr9Ld.png)

**Comment by atotic** [comment]
I can't tell what went wrong. File a separate bug with a reproducible case if you can.

**Comment by sonnythehottest** [comment]
@atotic hi, shouldn't we still be able to handle sign in, though the setting `block third party cookies...` is checked?

**Comment by atotic** [comment]
> @atotic hi, shouldn't we still be able to handle sign in, though the setting block third party cookies... is checked?

I do not think so, but I am not the expert.
