### ISSUE TITLE
New Google Logo

### ISSUE THREAD

**Issue by adefran83** [GoogleWebComponents/google-signin#106]
The logo on the icons is the old Google logo, I assume this will be updated to match the new styling?

**Comment by addyosmani** [comment]
@Zoramite do you know if there are plans to update the non-element version of this project to use the new logo? It's probably worth us aligning with the timelines on that for consistency.

**Comment by Zoramite** [comment]
I will check with the team to see what the plans are, but definitely need to update it with the updated branding.

**Comment by fiws** [comment]
..sooo???

**Comment by Zoramite** [comment]
@ebidel When you have time can you cut a new release with the updated branding?
