### ISSUE TITLE
Use on the server side

### ISSUE THREAD

**Issue by DmT021** [GoogleWebComponents/google-signin#107]
How do I use google-signin-aware with the server.
I have a SPA with a google-signin-aware. Also I have an api server.
I want to use sign in with google for authentification at my server.
I found, I can get access token in the handler of the google-signin-aware-success event.
I send it to the api server. Than on the server side I authorize with the access token on Google OAuth2 service and get user info.
Is this way correct?
If so, why there is no way to get access token from google-signin-aware without event handling?

**Comment by atotic** [comment]
Polymer does not run on the server. Use the auth2 library directly.
