### ISSUE TITLE
Doc is ambiguous if this is for Google Sign-In or Google+ Sign-In

### ISSUE THREAD

**Issue by agektmr** [GoogleWebComponents/google-signin#108]
Apparently this is using Google Sign-In because it's calling `auth2` but the documentation mentions some portion of Google+ APIs. It's nice to clarify that this is using Google Sign-In and it only loads relevant scopes.

**Comment by ebidel** [comment]
cc @addyosmani probably left over from the port. I know that if you request certain scopes (G+) it will actually use Google+ signin. Otherwise, the default is Google Sign in 2.0.

**Comment by atotic** [comment]
Can you be more explicit about where the ambiguity is? I've looked at the docs, and they explain G+ use cases.
