### ISSUE TITLE
gapi or auth2 inconsistently fail loading

### ISSUE THREAD

**Issue by geoffdavis92** [GoogleWebComponents/google-signin#116]
#### Issue: `gapi` and `auth2` fail loading inconsistently
Sometimes it's `gapi` that fails, other times I will refresh the page and find out that `auth2` failed.

Occasionally, I will refresh my page and the sign-in functionality works as intended. I thought the issue may be async loading of `gapi`/`auth2`, so I tried wrapping my Polymer-calling code in a `$(document.ready({...})` function, but that did not help.

This leads me to believe there is some sort of issue on Polymer's end; I may be wrong, but if there's any way to help, I would greatly appreciate it.

| Dependency             | Version  |
|-----------------------------|------------|
| Polymer                    | v1.2.0   |
| WebComponentsJS | v0.7.15 |
| Google-Signin          | v1.2.0   |

**Comment by atotic** [comment]
Can't help you with this without a reproducible case. Can you provide an example? What kind of errors are you seeing? Are libraries failing to load because of a network error?

**Comment by geoffdavis92** [comment]
@atotic Unfortunately I can't link you to my project, since it's using private data, but here are some screen shots: 
![jsloaded](https://cloud.githubusercontent.com/assets/7330124/10827491/5a442be8-7e3d-11e5-8e20-92b9ba29f12f.png)
![gapierror](https://cloud.githubusercontent.com/assets/7330124/10827494/5a48eb1a-7e3d-11e5-8df9-66c8f8f080a0.png)
![auth2error](https://cloud.githubusercontent.com/assets/7330124/10827493/5a4547c6-7e3d-11e5-8f13-d16fc7f31b62.png)
![htmlimports](https://cloud.githubusercontent.com/assets/7330124/10827492/5a452e94-7e3d-11e5-9021-a2cf45a524f1.png)

No network errors.

**Comment by atotic** [comment]
What's the stack trace of your error?
There is something specific to your setup causing this. I assume you've tried the demo pages in google-signin, and that they work.
Debugging it is about figuring out what exactly is failing, and then what's the cause.
Libraries are not loaded. It ;ooks like they are from the network. lines 310 is outside of any function. Are you using latest release? Set some breakpoints, dig in deep, see what you find out.
