### ISSUE TITLE
proxy prompt parameter for GoogleAuth.signIn

### ISSUE THREAD

**Issue by nodirt** [GoogleWebComponents/google-signin#128]
`google-signin-aware` indirectly calls [GoogleAuth.signIn](https://developers.google.com/identity/sign-in/web/reference#googleauthsigninwzxhzdk72optionswzxhzdk73) function. The function has `prompt` parameter, but `google-signin-aware` does not pass it, and there is no way to specify its value.

I'm ok implementing it, but wanted to discuss the design first:
- add `prompt` property to `AuthEngine`
- add `prompt` to `ProxyLoginAttributes` 
- add `prompt` property of type string to `google-signin-aware` element, sync its value with `AuthEngine`
- add the property to `google-signin` element

Suggestions for a better property name are welcome.

**Comment by atotic** [comment]
I have no idea what prompt does, but your design sounds sensible, follows the existing pattern.

**Comment by nodirt** [comment]
prompt allows the user to customize the workflow:

from the [spec](https://openid.net/specs/openid-connect-basic-1_0.html#RequestParameters):
```
prompt
  OPTIONAL. Space-delimited, case-sensitive list of ASCII string values that
  specifies whether the Authorization Server prompts the End-User for
  reauthentication and consent. The defined values are:
    none
      The Authorization Server MUST NOT display any authentication or consent
      user interface pages. An error is returned if an End-User is not already
      authenticated or the Client does not have pre-configured consent for the
      requested Claims or does not fulfill other conditions for processing the
      request. The error code will typically be login_required,
      interaction_required. This can be used as a method to check for existing
      authentication and/or consent.
    login
      The Authorization Server SHOULD prompt the End-User for reauthentication.
      If it cannot reauthenticate the End-User, it MUST return an error,
      typically login_required.
    consent
      The Authorization Server SHOULD prompt the End-User for consent before
      returning information to the Client. If it cannot obtain consent, it MUST
      return an error, typically consent_required.
    select_account
      The Authorization Server SHOULD prompt the End-User to select a user
      account. This enables an End-User who has multiple accounts at the
      Authorization Server to select amongst the multiple accounts that they
      might have current sessions for. If it cannot obtain an account selection
      choice made by the End-User, it MUST return an error, typically
      account_selection_required.
```

More context: I have two google accounts. If I sign in once, it remembers the account I used and never asks me again even if I sign out and try to sign in again. I will specify `prompt="select_account"` to fix that

**Comment by atotic** [comment]
Sounds useful.
