### ISSUE TITLE
iron-flex-layout-classes

### ISSUE THREAD

**Issue by AdamZiegler** [GoogleWebComponents/google-signin#132]
Line 8 of google-signin.html is using the old iron-flex method and is throwing errors:
`<link rel="import" href="../iron-flex-layout/classes/iron-flex-layout.html">`

Should be: 
`<link rel="import" href="../iron-flex-layout/iron-flex-layout-classes.html">`
or
`<link rel="import" href="../iron-flex-layout/iron-flex-layout.html">`

**Comment by arthurevans** [comment]
:+1: We should also replace the current link`<rel="import" type="css">` with a style module.

**Comment by ebidel** [comment]
@addyosmani can you look at this?
