### ISSUE TITLE
Unescaped </script> in JS comment leads to breakage

### ISSUE THREAD

**Issue by jeffposnick** [GoogleWebComponents/google-signin#133]
The escaping that was undone in https://github.com/GoogleWebComponents/google-signin/commit/89353ae016ff008a1b053fe6d1b6e51507a16ae4 is actually needed, and the current `master` version of `google-signin-aware.html` has a syntax error.

The unescapted `</script>` tag in the JavaScript comment ends up being interpreted as closing the top-level `<script>`.

![image](https://cloud.githubusercontent.com/assets/1749548/13967251/8a53e9fa-f04c-11e5-9ae5-104f22ff136c.png)

@Zoramite, can you revert https://github.com/GoogleWebComponents/google-signin/commit/89353ae016ff008a1b053fe6d1b6e51507a16ae4?

**Comment by ebidel** [comment]
This is what code reviewers are for :(

**Comment by Zoramite** [comment]
Rolled back in 46b97c9. Sorry for the trouble.
