### ISSUE TITLE
The documentation has some mistakes

### ISSUE THREAD

**Issue by LM450N** [GoogleWebComponents/google-signin#141]
During my last contribution I seen few mistakes in the documentation.

* default value of [brand](https://github.com/GoogleWebComponents/google-signin/blob/master/google-signin.html#L239)
* default value of [cookiePolicy](https://github.com/GoogleWebComponents/google-signin/blob/master/google-signin.html#L267)
* bad type on [height](https://github.com/GoogleWebComponents/google-signin/blob/master/google-signin.html#L277)
* type and default value of [theme](https://github.com/GoogleWebComponents/google-signin/blob/master/google-signin.html#L401)
* missing documentation...

For the missing documentation it seems not a big deal since the documentation engine looks smart enough to do introspection. Correct me if I'm wrong. :facepunch:

**Comment by atotic** [comment]
I think defaults are correct. These are actually the auth2 library defaults.
