### ISSUE TITLE
Support state parameter

### ISSUE THREAD

**Issue by silenceisgolden** [GoogleWebComponents/google-signin#19]
Currently there is no attribute available for adding a state parameter (CSRF). The pattern I have been using is the round trip the state parameter through the first call, then keep it through the rest of the hybrid auth process. This could possibly tie into adding support for the hybrid process, although I do not know if that is considered out of scope for this element. If this support can be added, however, this element would also need an ability to set `'postmessage'` appropriately as well as sending a request to the application server to have it verify the token. Refreshing the token would be necessary as well.

**Comment by atotic** [comment]
new version released, clearing out old bugs
