### ISSUE TITLE
chrome extension?

### ISSUE THREAD

**Issue by davidmaxwaterman** [GoogleWebComponents/google-signin#56]
Can this work in a chrome extension? I've not had any success

I'm specifically interested to see it used in code injected into a (3rd party) web page by a content script, where the origin of the web page is not the same as the redirect_url which is ```https://appid.chromiumapp.org/provider_cb```.

**Comment by Zoramite** [comment]
I haven't created a chrome extension with web components yet, but there should not be anything that would cause them to explicitly not work.

Off the top of my head, you may need to vulcanize the web components before using them in the extension. Also, you would need to make sure there are no security features that restrict you from adding scripts to the page.

Do you have any specific errors that you are seeing? What is working and what is not working with the extension?

**Comment by davidmaxwaterman** [comment]
We don't need to vulcanize since the web components are injected into a web app context by the content script - we're using other web components in the same context.

I'm afraid we've moved on since I was trying to use this. We ended up not using GoogleWebComponents at all, and instead use the http interfaces via core-ajax directly. We avoided using api keys (which would be very visible to anyone wanting to use our api quota in their own apps) by getting an oauth token from the background script.

I guess you can close this, unless you want to investigate this type of usage.
