### ISSUE TITLE
'google-signin-offline' events fired twice

### ISSUE THREAD

**Issue by plequang** [GoogleWebComponents/google-signin#65]
Hi,
Under some circumstances, the event 'google-signin-offline' is fired twice. 

I've used the following code in the demo.html page to reproduce the issue :
```html
    <google-signin
        clientId="xxxxxxx.apps.googleusercontent.com"
        offline="true"
        scopes="email" 
        width="wide" height="tall" 
        cookiePolicy="single_host_origin">
    </google-signin>


    <script>
        document.addEventListener("google-signin-offline", function (e) {
            console.log('received google-signin-offline event', e);
            // my usage of one time auth code here
        });
    </script>
```
The event is fired twice only when the user sign in for the first time, i.e. when he his prompted for consent. 
Looking  at the stack trace, I've found that the event 'core-signal-google-auth-result'is fired once from the gloabally defined callback in the meta tag, and once from the 'callback' parameter of the signIn method.

According to this : https://developers.google.com/+/web/signin/reference#page-config, this should not happen, but it does (again, only when after sign-in with the consent screen).

In my situation, this results in sending twice the authorization code to my server, which will try to exchange it twice with google API server.

In google-signin.html, there is the following code in the authResult method :
```javascript
    // Only let the global defaultHandler trigger result signals to prevent fanning.
    if (this === defaultHandler && response.isGlobal) {
```
Would it be possible to add the same logic for firing the google-signin-offline event ?
Actually, the same applies to the 'google-signin-success' event.

Thanks
Pascal

**Comment by Zoramite** [comment]
As an update to this. There was a recent `0.3.0` release that should fix a lot of the double triggering issues. Unfortunately for this issue, the update also removed the `offline` attribute until I can get it working correctly with the updated API.

**Comment by plequang** [comment]
Thanks for the notice.
Actually, we had to move to Google OAuth signin, because we had issues with Google+ signin on phones (because it uses a popup window).

**Comment by Zoramite** [comment]
@plequang What issues were you seeing on mobile? If you could open another bug with the issued you are seeing on mobile I can look into it more. Mobile is one of the places it should definitely work, so we need to improve it if it is not working correctly.

**Comment by plequang** [comment]
Actually @nomego already reported issue #60 (We are working together on the same project).

As it seemed to be more a device issue rather than a google signin issue, I decided to move to "traditional oauth" as described here https://developers.google.com/accounts/docs/OpenIDConnect.

This solution works with iphone and android phones (and even with my windows phone, but that's not the main target).

**Comment by Zoramite** [comment]
Thanks @plequang I'm looking into that issue more to see if I can reproduce it and figure out what is happening. I'll close this issue for now.

**Comment by voxmatt** [comment]
@Zoramite did you ever figure this out? we also see the google api storing previous callbacks and calling them all with all previous results, not even using your component library but using the api directly

**Comment by atotic** [comment]
google-signin has been extensively refactored for Polymer 1.0. It is not supporting offline right now, but it can if there is interest, and you guys come up with a design.
