### ISSUE TITLE
Delayed creation of signin button and immediate signin

### ISSUE THREAD

**Issue by mnieper** [GoogleWebComponents/google-signin#66]
If the <google-signin> element is not created timely, an already authorized user is not signed in automatically.

**Comment by Zoramite** [comment]
@mnieper Can you try updating to the `0.3.0` version and also using the `<google-signin-aware>` component to watch for a login change? I am curious if this removes the race conditions that you are seeing.

**Comment by atotic** [comment]
Library rewritten, this should work. Reopen if not.
