### ISSUE TITLE
Uncaught ReferenceError: gapi is not defined

### ISSUE THREAD

**Issue by mnieper** [GoogleWebComponents/google-signin#68]
This error is shown in the console under the following circumstances:

1) There is a `<google-signin>` element on the page.
2) There is a `<google-signin-aware>` element on the page.
3) The `<google-signin-aware>` element is `domReady` before gapi has been initialized (see https://github.com/GoogleWebComponents/google-signin/blob/master/google-signin.html#L314).

The error is generated at  https://github.com/GoogleWebComponents/google-signin/blob/master/google-signin.html#L314.

**Comment by Zoramite** [comment]
This should be fixed with the changes to version `0.3.0` sorry for the long delay.
