### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clear' of null

### ISSUE THREAD

**Issue by vl4dt** [GoogleWebComponents/google-signin#71]
I keep getting this error when trying to sign out:

    Uncaught TypeError: Cannot read property 'clear' of nullcb=gapi.loaded_0:473 
    Fscb=gapi.loaded_0:493 
    jxcb=gapi.loaded_0:503 
    (anonymous function)google-signin.html:641 
    Polymer.signOutevents.js:40 
    events.dispatchMethodevents.js:73 
    events.getEventHandler

**Comment by StevenDewey** [comment]
I'm getting the exact same error...

**Comment by Zoramite** [comment]
Is this a transient error, or does it happen every time? Can you give an example of how you are using the signin button when it fails?

**Comment by timbunch** [comment]
I'm getting the same error. Wondering if it's related to this: http://stackoverflow.com/questions/23153931/error-calling-signout-after-gapi-auth-authorize

**Comment by Zoramite** [comment]
Can you try with the `0.3.0` version and see if you are still seeing this error?

**Comment by atotic** [comment]
New version released.
