### ISSUE TITLE
Separate the client-id from the html

### ISSUE THREAD

**Issue by wburgers** [GoogleWebComponents/google-signin#73]
Hi guys,

I have a question:
Is it possible to inject the client-id later using JS/Polymer?
I tried data binding the client-id into the google-signin element.
This breaks the login.

I want to create an app where all settings are in a different settings.js file.
The client-id I use personally, can't be used by other apps, because it is set to my URL in the api console.
But still it would be nice to separate this from the element declaration, to ensure better portability.

I really love Polymer.
Keep it up!

**Comment by ebidel** [comment]
Data binding to clientId should work. Can you provide a jsbin of what's not working?

**Comment by Zoramite** [comment]
The check for the `clientID` happens when attached. We could move the check over to when attempting to signin which might help with the timing. I'm not sure when the data binding actually occurs in regards to the `attached` event.

**Comment by ebidel** [comment]
You could use a `clientIdChanged` to react to that property changing at any time (at init or later).

**Comment by Zoramite** [comment]
With the changes to `gapi.auth2` I need to `init` the auth after loading `auth2` to trigger the immediate auth. Calling the `init` with different a different options throws errors after it has been called once. 

I could watch the `clientId` for changes and check the value on attach. Whichever has a value first would `auth2.init` and any other changes would be ignored.

Does that sound like a reasonable approach. Or any less complex solutions?

**Comment by ebidel** [comment]
:+1:

**Comment by wburgers** [comment]
Sorry for my late response.
The problem is indeed that the connection attempt to the auth api happens when the element is declared, but data-binding happens later.

The solution looks solid.
Hope to see it implemented soon.

Thanks for both your fast responses (even on a sunday Eric! :+1: )

**Comment by atotic** [comment]
Fixed in the latest release.
