### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by addyosmani** [GoogleWebComponents/google-signin#75]
- [x] Author release notes
- [X] Bump bower.json to 0.3.0
- [X] Review and land new implementation
- [X] Tag new version
- [x] Publish new version to gh-pages
- [x] Investigate support for 0.3.0 in GWC elements using us as a dep

**Comment by addyosmani** [comment]
cc @Zoramite

**Comment by Zoramite** [comment]
Updated the [docs](http://googlewebcomponents.github.io/google-signin/components/google-signin/), [demo](http://googlewebcomponents.github.io/google-signin/components/google-signin/demo.html), and the [release notes](https://github.com/GoogleWebComponents/google-signin/releases/tag/v0.3.0) for the new version.

The updates to other GWC elements are in flight.
