### ISSUE TITLE
error: "internal_failure" when using 0.3.0 version with multiple accounts

### ISSUE THREAD

**Issue by gattasrikanth** [GoogleWebComponents/google-signin#77]
I tried this demo page at http://googlewebcomponents.github.io/google-signin/components/google-signin/demo.html with multiple google accounts signed in. Primary being gmail and secondary being a work account. When I clicked on Sign in account chooser is displayed, i Selected work account and its not signed in.
Below messages seen in console:
https://drive.google.com/file/d/0B71T1vBlMJ88YW90WTl1RkZLZlU/preview
If both the accounts are gmail.com accounts then its working fine.

**Comment by gattasrikanth** [comment]
On further checking, this seems like happening because the second account doesn't have a Google+ profile created? Although I am seeing a Blue color buttons which means "scopes that are not related to Google+" from release notes. In the networks tab of chrome i see the scope parameters as "scope:openid profile email http://my_scoce/...". I have only mentioned the url, but somehow it is adding "openid profile email" is that causing the issue?

**Comment by ebidel** [comment]
@Zoramite @gguuss are you guys aware of API issues?

**Comment by Zoramite** [comment]
Those scopes shouldn't have any requirements for G+ and they would show the upgrade flow if they did. I'll test it out and see if I can find out what is happening.

**Comment by gattasrikanth** [comment]
Any update? or need any other info to repro?

**Comment by Zoramite** [comment]
@gattasrikanth We are looking into things and I'll let you know when we have an update.

**Comment by gattasrikanth** [comment]
Thanks for looking into.

**Comment by Zoramite** [comment]
Hi @gattasrikanth can you try this again and see if it is still an error? A fixed was pushed out today and from my testing it appears to work, but if you could verify then we can close this issue.

**Comment by gattasrikanth** [comment]
FIXED!!! Thanks for the fix.
