### ISSUE TITLE
google-signin-success fires before a profile is chosen

### ISSUE THREAD

**Issue by TheMallen** [GoogleWebComponents/google-signin#78]
It seems to me that `google-signin-success` is fired when the authentication credentials are validated. There is no documented event for when a profile is chosen. This makes it overly difficult to build an application which cares what profile you have chosen. If there is something I am missing please let me know :)

**Comment by Scarygami** [comment]
The event details you get once the event is triggered include the user object with details about the authenticated user:
https://github.com/GoogleWebComponents/google-signin/blob/master/google-signin.html#L285

**Comment by TheMallen** [comment]
That's not what I'm getting at. Here's the flow that occurs when I use the element:
1. I click the button
2. A popup appears asking which account I want to use
3. I click the account I want
4. The ui elements which I told to listen for the event fire twice
OR
5. The ui elements which I told to listen to the event fire once, but only when I first clicked the button, not once I selected an account
OR
6. The `google-signin-success` event is never triggered.

I am not sure why.The second two cases seem to occur when trying to sign in and out between multiple profiles without reloading the page.

**Comment by TheMallen** [comment]
It seems to me to that triggering 'google-signin-success' is counterintuitive for an 'authUserChange' handler. Shouldn't the user changing be it's own event from the perspective of listeners?

**Comment by Zoramite** [comment]
Thanks for bringing this up @TheMallen. The idea was to call the event any time there is a change to the user, but you are correct, that probably isn't the expected behavior for a success event.

I will change it to only send the `google-signin-success` to only trigger when a signed in user is found the first time with all the required permissions granted.

**Comment by TheMallen** [comment]
Sounds like a good idea :)
