### ISSUE TITLE
returned user on `` event

### ISSUE THREAD

**Issue by matantsu** [GoogleWebComponents/google-signin#81]
I added the element and attached an `eventListener`:
```
var gs = document.getElementById('testing');
        gs.addEventListener('google-signin-success' , function(e){
            console.log(e);
        });
```

here is the JSON representation of `e.detail.user`:
```
"{
	"El": "105333455535789574914",
	"UT": null,
	"B": {
		"G": "105333455535789574914",
		"ha": "??? ?????",
		"B": "matantsuberi@gmail.com"
	}
}"
```

what are the `El` `UT` `B` `B.G` , `B.ha` `B.B` fields ?
Is it a problem with the library ?

**Comment by Zoramite** [comment]
Hi @matantsu 

The user is an instance of the [`gapi.auth2.GoogleUser`](https://developers.google.com/identity/sign-in/web/reference#gapiauth2googleuser) object. You can use the accessor functions to retrieve the specific information from the user object.

For example: `user.getId()` or `user.getBasicProfile().getName()`

**Comment by matantsu** [comment]
thanks
