### ISSUE TITLE
Problems with Phonegap and Android

### ISSUE THREAD

**Issue by prateekjadhwani** [GoogleWebComponents/google-signin#82]
I implemented the google-signin element in my custom element. It works fine on the browser, but fails to work in hybrid app build on phonegap. The error that I got is as follows

```
Uncaught gapi.auth2.ExternallyVisibleError: Invalid cookiePolicy        cb=gapi.loaded_0:119
Uncaught TypeError: Cannot read property 'signIn' of undefined          google-signin.html:551
Polymer.signIn                                                          google-signin.html:551
  events.dispatchMethod                                                 polymer.js:9131
  (anonymous function)                                                  polymer.js:10715
```

I am not sure why `auth` is undefined here, it seems as if the `gapi` library is not initializing. I could be wrong.

**Comment by Zoramite** [comment]
Hi @prateekjadhwani it looks like it received an invalid value for the `cookiePolicy`. Are you using a custom value to the `cookiePolicy`?

**Comment by prateekjadhwani** [comment]
As far as I know, I am not changing anything to `cookiePolicy` at all. 

```
<google-signin
            clientId="{{clientID}}"
            scopes="https://www.googleapis.com/auth/plus.login"
            labelSignin="Sign In with Google Plus"    
            height="tall"
            width="wide"
            google-signin-success="{{handleSignIn}}"
            google-signin-failure="{{handleSignInFailure}}">
 </google-signin>
```

This is what I am adding to my file. So that code is not changing `cookiePolicy` at all. After some research I found that PhoneGap uses `localStorage` and/or `sessionStorage` to maintain/keep track of cookies. 

Sources : 
- http://stackoverflow.com/questions/15349237/handling-cookies-in-phonegap-cordova
- http://stackoverflow.com/questions/23471256/not-getting-cookies-in-android-phonegap-application
- https://github.com/phonegap/phonegap-app-developer/issues/231

Not sure if that helps, but is there a fallback for `Invalid cookiePolicy` which can be used to make it work until the bug can be fixed at PhoneGap's end.

**Comment by Zoramite** [comment]
You can try to add `cookiePolicy="none"` to see if that allows it to go through. There are only two options, the default single host origin and none. So if the single host is not working the `none` is the only other valid option.

**Comment by prateekjadhwani** [comment]
Nope, doesn't work. It still breaks.

**Comment by Zoramite** [comment]
Hmm.. sorry, It sounds like they don't have normal cookie usage. Currently we don't have any plans to support the alternatives that PhoneGap currently support. Going to close this issue for now. If PhoneGap gets support for cookies and it still doesn't work then we can look at it more.

**Comment by prateekjadhwani** [comment]
No Worries. Thank you for your time.

**Comment by nickcarenza** [comment]
Having a similar issue with electron.

**Comment by Miguel222tm** [comment]
hello guys, did you find any solutions for othis issue?

**Comment by atotic** [comment]
My guess: Since phonegap website on a phone is served statically from arbitrary `file://` urls, the website-style oauth2 would not work because of origin restrictions.

You might have success if you treat your site as an installed app instead. Looks like that involves using a different clientID:
https://developers.google.com/identity/protocols/OAuth2InstalledApp
