### ISSUE TITLE
`offline` attribute support

### ISSUE THREAD

**Issue by Zoramite** [GoogleWebComponents/google-signin#86]
The older version of the web component had support for the `offline` attribute. Need to bring this back to the latest version. There was previously a bug that prevented it from working correctly. The bug should be fixed now. Need to test and add the logic back into the component.

**Comment by davidcv5** [comment]
@Zoramite are you going to include "Google Sign-In for server-side apps" or "OAuth 2.0 for Web Server Applications", or maybe both?

Asking because the one allows over the air installs, but the other doesn't.

https://developers.google.com/identity/sign-in/web/server-side-flow

Thanks!!!

**Comment by jmorille** [comment]
Any news about the support of the offline token ?

**Comment by davidcv5** [comment]
@jmorille I forked this repo and added that offline capability.. in case you're interested..you can see it here https://github.com/davidcv5/google-signin
At least until they release the official one... I PR it but they told me it was coming soon so didn't accept it. But could save you sometime until then... good luck!

**Comment by Zoramite** [comment]
Thanks for the bump on this. I've finished this up and made PR #89 for the changes.

**Comment by davidcv5** [comment]
Awesome! Thanks a lot @Zoramite

**Comment by atotic** [comment]
@davidcv5 @jmorille We've just released 1.0 version of google-signin, and I did the port. Architecture is slightly different from 0.5 version. Offline support sounds like a good feature to add. But I am a Polymer guy, not a Google auth guy. If you guys would like to walk me through what's needed, we can add it.

**Comment by Compufreak345** [comment]
+1

**Comment by Zoramite** [comment]
@atotic this was the original change that I was going to add it back in originally before the rewrite: https://github.com/GoogleWebComponents/google-signin/compare/api2.0-offline

**Comment by yesthatguy** [comment]
Thanks all! @atotic I'm not a super expert in the Google signin flow but know a bit and would love to use the offline support in polymer, so if there's anything I can do to help let me know.

**Comment by atotic** [comment]
Implemeneted in 2d6131495c3977d6d1cc863847b6713b39f82be2
