### ISSUE TITLE
Not getting user info on signin

### ISSUE THREAD

**Issue by losttime** [GoogleWebComponents/google-signin#91]
I'm using the element with Polymer 1.0. When a user signs in, I'm getting the signin success event, but not getting the user data.

I've followed the stack trace and it looks like the data is coming into the site, but not percolating up to my app.

The `google-signin-aware` element fires a `google-signin-aware-success` event that includes the user data, but the `google-signin` element doesn't catch this event and add the data to its own "success" event.

Should I be listening to the event fired by `google-signin-aware`, or does `google-signin` need to be updated to add the user data to its success event?

**Comment by atotic** [comment]
you should listen to google-signin-aware. We've revamped google-signin element for 1.0, and docs did not get updated.
