### ISSUE TITLE
Uncaught TypeError: Cannot read property 'currentUser' of null

### ISSUE THREAD

**Issue by baole** [GoogleWebComponents/google-signin#93]
I use this component with Polymer/Polymer Web Starter Kit as follow

In elements.html
<link rel="import" href="../bower_components/google-signin/google-signin.html">
<link rel="import" href="../bower_components/google-signin/google-signin-aware.html">

In index.html
<google-signin clientId="xxxxx.apps.googleusercontent.com" scopes="profile"></google-signin>

When run with gulp command, and click on Signin button, following exception logged

Uncaught TypeError: Cannot read property 'currentUser' of null
AuthEngine.signIn @ google-signin-aware.html:315
Polymer.signIn @ google-signin-aware.html:480
Polymer.signIn @ google-signin.html:456
(anonymous function) @ polymer.html:347
decorated @ polymer.html:3019

Any help?

**Comment by moneal** [comment]
I'm having the same problem.

**Comment by moneal** [comment]
Looks like the documentation is wrong in a lot of spots or the code has the wrong parameter name. Changing `clientId` to `client-id` worked for me. Total call now looks like `<google-signin client-id="..." scopes="https://www.googleapis.com/auth/drive"></google-signin>`

**Comment by baole** [comment]
Thanks Moneal. Change to client-id works great for me.

**Comment by atotic** [comment]
Documentation was out of date, and the error thrown was not helpful. Fixing.

**Comment by tregoning** [comment]
just FYI it looks like https://elements.polymer-project.org/elements/google-signin (is still out of date)

**Comment by Scarygami** [comment]
I assume they have an internal cycle for creating new releases of updated components and pushing them to the catalog. 

Would be interesting to know how frequently this is done though, I'm waiting for some releases in other components as well :)
